name: insitu-glo-2020-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - shapely
  - folium
  - pip
  - pip:
    - IPython
    - pandas
    - json2html
    - ftputil
    - matplotlib
    - netCDF4
    - xarray
    - branca